// Package ontology holds the committed v0 graph model — the RDF TBox (ontology.ttl), the SKOS
// domain vocabulary (vocab.ttl), and the SHACL shapes (shapes.ttl) — and embeds them so a Go
// binary (the load path) is self-contained.
//
// The .ttl files are the canonical artifacts (authored/reviewed here, vocab.ttl generated by
// generate_vocab.py). They live in this directory rather than under load/graph/ because an
// embed directive can only reach files within its own package tree; load/graph imports this
// package's embedded bytes instead of duplicating the files.
package ontology

import _ "embed"

// Ontology is the RDF TBox (classes, properties, uncertainty/temporal/caveat terms).
//
//go:embed ontology.ttl
var Ontology []byte

// Vocab is the SKOS domain vocabulary (ConceptScheme, concepts, labels, hierarchy).
//
//go:embed vocab.ttl
var Vocab []byte

// Shapes is the SHACL shapes graph the load gate validates candidate graphs against.
//
//go:embed shapes.ttl
var Shapes []byte
